project:
  type: website
  output-dir: docs
   

website:
  title: "Emmanuel Felipe Patriota de Albuquerque"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Consumption"
        menu:
          - text: "Influences"
            href: consumption/consumption-influences.qmd
          - text: "Practices"
            href: consumption/consumption-practices.qmd
          - text: "Videos"
            href: consumption/consumption-videos.qmd
          - text: "Books"
            href: consumption/consumption-books.qmd
          - text: "Papers"
            href: consumption/consumption-papers.qmd
          - text: "Podcasts"
            href: consumption/consumption-podcasts.qmd
      - text: "Production"
        menu:
          - text: "Research"
            href: production/production-research.qmd
          - text: "Tutoring"
            href: production/production-tutoring.qmd
          - text: "Misc. Writings"
            href: production/production-m-writings.qmd
          - text: "Entrepreneurship"
            href: production/production-entrepreneurship.qmd            
      - text: "About"
        href: about.qmd
        menu:
          - text: "Biography"
            href: biography.qmd
          - text: "CV"
            href: cv.qmd
          - text: "Awards"
            href: awards.qmd        
      - text: "Contact"
        href: contact.qmd
  draft-mode: gone
format:
  html:
    css: styles.css
    theme:
      dark: darkly
      light: flatly
      
metadata-files:
  - drafts.yml