---
title: "misc writings"
format: html
---

# Consumption meets Production

## Thoughts after listening to Mill on Utilitarianism

Utilitarianism as an approach to ethics. 

Responding to a criticism of utilitarianism that persists to this day, Mill remarked that it is not necessary to perform utility calculations on the spot, in the same way that to be observant of religious practices one does not have to read scripture on the spot. Calculations about utility and about what is pleasurable or desirable have long been the occupation of humanity (for as long as parents have said "this is good, my child" and as children grew into adulthood and decided for themselves what was desirable or not.)

(This is not to say that calculations are complete. They are always in the making. The better understanding of causal connections between intermediary and final objectives, for example, changes what we think is desirable.)

## To what extent is reason a guiding principle to the Australian governance?



## 